my_robot:
    #list of controllers
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    camera_platform_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: camera_platform_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
